server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyId: LTAI5tJzGVBadmgRy2EgivKg
    keySecret: 60gCiVuW55fxYR57HmxlVHxZcLhYyo
    bucketName: mch-srb


