server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      server-addr: 192.168.14.111:8848
  #spring:
  redis:
    host: menchuanhe.top
    port: 6379
    database: 0
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20
  rabbitmq:
    host: 192.168.14.111
    port: 5672
    virtual-host: /srbhost
    username: srbuser
    password: 123456
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true
#阿里云短信
aliyun:
  sms:
    appSecret: OrqD1sE278nzYqJ4JvgdFQ7iWLvBh0t1
    appCode: 7d443865a56f4cacb9ac6c18d3b5729a
    host: http://dingxin.market.alicloudapi.com
    path: /dx/sendSms
    method: POST
    templateId: TP1711063
logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: debug
